### PR TITLE
Add Hindi translation

### PR DESCRIPTION
**Pull request by 2KAbhishek**
Added Hindi translation example

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by bl-ue** [comment]
@marchersimon you can just close this one.

**Comment by bl-ue** [comment]
@ 2KAbhishek already submitted a translation [here](https://github.com/tldr-pages/tldr/pull/5988#discussion_r635440953).

**Comment by marchersimon** [comment]
Ah, thanks, I'm still trying to catch up with all my notifications 😄

**Comment by bl-ue** [comment]
I know! I was just thinking the same thing! Busy day 🤷🏻‍♂️

**Pull request closed without merging**
